# Basic Python

## 1. Split this string

In [29]:
s = "Hi there Sam!"
s

'Hi there Sam!'

In [30]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [35]:
str="The diameter of {planet} is {diameter} kilometers".format(planet = "Earth",diameter = 12742)
str

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d

{'k1': [1,
  2,
  3,
  {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]}

In [16]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [25]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [2]:
import numpy as np

In [3]:
array=np.arange(20,35,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
import numpy as np

In [5]:
d1=np.arange(9).reshape(3,3)
d1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
ab=np.concatenate((a,b),axis=0)
ab

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [8]:
import pandas as pd


In [4]:
df=pd.DataFrame({'col1':['A11','A21','A31'],'col2':['A12','A22','A32']})
df.index=['row1','row2','row3']
df

col1 col2
row1  A11  A12
row2  A21  A22
row3  A31  A32

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [9]:
pd.date_range(start='1st/jan/2023',end='10th/feb/2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [11]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24

In [13]:
df.ndim

2